apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpgittest-serviceone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpgittest-serviceone
  template:
    metadata:
      annotations:
        redeploy: 'true'
      labels:
        app: phpgittest-serviceone
    spec:
      containers:
      - image: 672072155362.dkr.ecr.us-east-1.amazonaws.com/testecr:latest
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8003
          initialDelaySeconds: 180
          periodSeconds: 5
        name: testcont
        ports:
        - containerPort: 8003
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: serviceone-service
spec:
  ports:
  - port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    app: phpgittest-serviceone
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: 'true'
  name: my-aws-ingress-class
spec:
  controller: ingress.k8s.aws/alb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/load-balancer-name: phpgittest-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-0c5373ad69f0b46c7, subnet-0e59bc73ce442dd84
    alb.ingress.kubernetes.io/success-codes: 200-404
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  labels:
    app: app-phpgittest
  name: ingress-phpgittest
spec:
  defaultBackend:
    service:
      name: serviceone-service
      port:
        number: 8003
  ingressClassName: my-aws-ingress-class
